#/appspec.yml
version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/deploy/
permissions:
  - object: /
    pattern: "**"
    mode: 755
    owner: root
    group: root
hooks:
  BeforeInstall:
    - location: scripts/stopDocker.sh
      timeout: 300
  AfterInstall:
    - location: scripts/pullDocker.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/runDocker.sh
      timeout: 300


