#/appspec.yml
version: 0.0
os: linux
files:
  - source: /
    destination: /deploy
    runas: ubuntu
hooks:
  AfterInstall:
    - location: scripts/pullDocker.sh
      timeout: 120

  ApplicationStart:
    - location: scripts/runDocker.sh
      timeout: 60

  ApplicationStop:
    - location: scripts/stopDocker.sh
      timeout: 60
